[package]
name = "bigquery-storage"
version = "0.1.2"
authors = ["damien <damien@openquery.io>"]
description = "A small wrapper around the Google BigQuery Storage API"
keywords = [ "google", "bigquery", "storage" ]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/openquery-io/bigquery-storage"
readme = "README.md"

[lib]
# Google's protos have comments with code blocks. Tonic will write these
# comments as docs in the generated files, and since they include code blocks
# that aren't valid Rust, they fail the doc tests. Rust doesn't have a way of
# disabling doc tests for a single module, and I could not figure out how to get
# tonic to not include comments in the generated files.
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "arrow" ]

[build-dependencies]
tonic-build = "0.8.0"

[dev-dependencies]
tokio = { version = "1.0", features = [ "rt", "macros" ] }

[dependencies]
futures = "0.3"
tonic = { version = "0.8.0", features = ["transport", "tls", "tls-roots"] }
prost = "0.11.0"
prost-types = "0.11.0"

yup-oauth2 = { version = "5.0" }
hyper = { version = "0.14" }

arrow = { version = "3.0", optional = true }
