name: CI

on: [push, workflow_dispatch]

jobs:
  tests:
    name: tests
    runs-on: ubuntu

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cargo Test
      env:
        SA: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        echo $SA > clientsecret.json
        cargo test

    - name: Clippy
      run: cargo clippy --all-features -- --deny warnings
